# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConexVista.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_conexWindow(object):
    def setupUi(self, conexWindow):
        conexWindow.setObjectName("conexWindow")
        conexWindow.resize(302, 329)
        self.centralwidget = QtWidgets.QWidget(conexWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(237, 250, 254);")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(237, 250, 254);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.vel = QtWidgets.QLabel(self.frame)
        self.vel.setObjectName("vel")
        self.gridLayout.addWidget(self.vel, 0, 0, 1, 1)
        self.vel_motor = QtWidgets.QLineEdit(self.frame)
        self.vel_motor.setText("")
        self.vel_motor.setObjectName("vel_motor")
        self.gridLayout.addWidget(self.vel_motor, 0, 2, 1, 1)
        self.deteccion = QtWidgets.QLabel(self.frame)
        self.deteccion.setObjectName("deteccion")
        self.gridLayout.addWidget(self.deteccion, 1, 0, 1, 1)
        self.ran_detec = QtWidgets.QLineEdit(self.frame)
        self.ran_detec.setText("")
        self.ran_detec.setObjectName("ran_detec")
        self.gridLayout.addWidget(self.ran_detec, 1, 2, 1, 1)
        self.alpha = QtWidgets.QLabel(self.frame)
        self.alpha.setObjectName("alpha")
        self.gridLayout.addWidget(self.alpha, 2, 0, 1, 2)
        self.thetha_luz = QtWidgets.QLineEdit(self.frame)
        self.thetha_luz.setText("")
        self.thetha_luz.setObjectName("thetha_luz")
        self.gridLayout.addWidget(self.thetha_luz, 2, 2, 1, 1)
        self.tiempo = QtWidgets.QLabel(self.frame)
        self.tiempo.setObjectName("tiempo")
        self.gridLayout.addWidget(self.tiempo, 3, 0, 1, 1)
        self.tiempo_prueba = QtWidgets.QLineEdit(self.frame)
        self.tiempo_prueba.setText("")
        self.tiempo_prueba.setObjectName("tiempo_prueba")
        self.gridLayout.addWidget(self.tiempo_prueba, 3, 2, 1, 1)
        self.tiempo_2 = QtWidgets.QLabel(self.frame)
        self.tiempo_2.setObjectName("tiempo_2")
        self.gridLayout.addWidget(self.tiempo_2, 4, 0, 1, 1)
        self.Lux_lit = QtWidgets.QLineEdit(self.frame)
        self.Lux_lit.setText("")
        self.Lux_lit.setObjectName("Lux_lit")
        self.gridLayout.addWidget(self.Lux_lit, 4, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 5, 0, 1, 1)
        self.Tmax_var = QtWidgets.QLineEdit(self.frame)
        self.Tmax_var.setText("")
        self.Tmax_var.setObjectName("Tmax_var")
        self.gridLayout.addWidget(self.Tmax_var, 5, 2, 1, 1)
        self.enviarButton = QtWidgets.QPushButton(self.frame)
        self.enviarButton.setObjectName("enviarButton")
        self.gridLayout.addWidget(self.enviarButton, 6, 0, 1, 1)
        self.levelbutton = QtWidgets.QPushButton(self.frame)
        self.levelbutton.setObjectName("levelbutton")
        self.gridLayout.addWidget(self.levelbutton, 6, 1, 1, 2)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        conexWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(conexWindow)
        QtCore.QMetaObject.connectSlotsByName(conexWindow)

    def retranslateUi(self, conexWindow):
        _translate = QtCore.QCoreApplication.translate
        conexWindow.setWindowTitle(_translate("conexWindow", "Conexión"))
        self.vel.setText(_translate("conexWindow", "PWM "))
        self.deteccion.setText(_translate("conexWindow", "rango de detección"))
        self.alpha.setText(_translate("conexWindow", "variable thetha de luz"))
        self.tiempo.setText(_translate("conexWindow", "tiempo de pruebla"))
        self.tiempo_2.setText(_translate("conexWindow", "lux"))
        self.label.setText(_translate("conexWindow", "Tmax"))
        self.enviarButton.setText(_translate("conexWindow", "Enviar"))
        self.levelbutton.setText(_translate("conexWindow", "Calibrar sensores de distancia"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    conexWindow = QtWidgets.QMainWindow()
    ui = Ui_conexWindow()
    ui.setupUi(conexWindow)
    conexWindow.show()
    sys.exit(app.exec_())
