# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EnjambreMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(768, 441)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.PrincipalFrame = QtWidgets.QFrame(self.centralwidget)
        self.PrincipalFrame.setGeometry(QtCore.QRect(0, 0, 771, 511))
        self.PrincipalFrame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.PrincipalFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PrincipalFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PrincipalFrame.setObjectName("PrincipalFrame")
        self.Lateral = QtWidgets.QFrame(self.PrincipalFrame)
        self.Lateral.setGeometry(QtCore.QRect(0, -10, 51, 451))
        self.Lateral.setStyleSheet("background-color: rgb(196, 238, 250);")
        self.Lateral.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Lateral.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Lateral.setObjectName("Lateral")
        self.SwarButton = QtWidgets.QPushButton(self.Lateral)
        self.SwarButton.setGeometry(QtCore.QRect(0, 0, 51, 51))
        self.SwarButton.setObjectName("SwarButton")
        self.TestButton = QtWidgets.QPushButton(self.Lateral)
        self.TestButton.setGeometry(QtCore.QRect(0, 80, 51, 51))
        self.TestButton.setObjectName("TestButton")
        self.AboutButton = QtWidgets.QPushButton(self.Lateral)
        self.AboutButton.setGeometry(QtCore.QRect(0, 390, 51, 51))
        self.AboutButton.setObjectName("AboutButton")
        self.ResuButton = QtWidgets.QPushButton(self.Lateral)
        self.ResuButton.setGeometry(QtCore.QRect(0, 160, 51, 51))
        self.ResuButton.setObjectName("ResuButton")
        self.ConexionButton = QtWidgets.QPushButton(self.Lateral)
        self.ConexionButton.setGeometry(QtCore.QRect(0, 250, 51, 51))
        self.ConexionButton.setObjectName("ConexionButton")
        self.Bloque2 = QtWidgets.QFrame(self.PrincipalFrame)
        self.Bloque2.setGeometry(QtCore.QRect(50, 0, 361, 221))
        self.Bloque2.setStyleSheet("background-color: rgb(237, 250, 254);")
        self.Bloque2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Bloque2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Bloque2.setObjectName("Bloque2")
        self.playButton = QtWidgets.QPushButton(self.Bloque2)
        self.playButton.setGeometry(QtCore.QRect(80, 20, 41, 41))
        self.playButton.setStyleSheet("color: rgb(0, 255, 255);")
        self.playButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../recursos/Play2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playButton.setIcon(icon)
        self.playButton.setIconSize(QtCore.QSize(30, 30))
        self.playButton.setObjectName("playButton")
        self.pauseButton = QtWidgets.QPushButton(self.Bloque2)
        self.pauseButton.setGeometry(QtCore.QRect(140, 20, 41, 41))
        self.pauseButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../recursos/pause2svg.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pauseButton.setIcon(icon1)
        self.pauseButton.setIconSize(QtCore.QSize(30, 30))
        self.pauseButton.setObjectName("pauseButton")
        self.stopButton = QtWidgets.QPushButton(self.Bloque2)
        self.stopButton.setGeometry(QtCore.QRect(200, 20, 41, 41))
        self.stopButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../recursos/stop (1).svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon2)
        self.stopButton.setIconSize(QtCore.QSize(30, 30))
        self.stopButton.setObjectName("stopButton")
        self.name = QtWidgets.QLineEdit(self.Bloque2)
        self.name.setGeometry(QtCore.QRect(10, 110, 81, 21))
        self.name.setStyleSheet("font: 12pt \"Tahoma\";\n"
"color: rgb(68, 169, 197);\n"
"")
        self.name.setObjectName("name")
        self.dataname = QtWidgets.QLabel(self.Bloque2)
        self.dataname.setGeometry(QtCore.QRect(10, 80, 131, 16))
        self.dataname.setStyleSheet("font: 10pt \"Tahoma\";\n"
"color: rgb(68, 169, 197);\n"
"")
        self.dataname.setObjectName("dataname")
        self.namelabel = QtWidgets.QLabel(self.Bloque2)
        self.namelabel.setGeometry(QtCore.QRect(10, 130, 161, 16))
        self.namelabel.setStyleSheet("font: 10pt \"Tahoma\";\n"
"color: rgb(68, 169, 197);\n"
"")
        self.namelabel.setObjectName("namelabel")
        self.Fecha = QtWidgets.QDateEdit(self.Bloque2)
        self.Fecha.setGeometry(QtCore.QRect(220, 160, 110, 22))
        self.Fecha.setStyleSheet("font: 12pt \"Tahoma\";\n"
"color: rgb(68, 169, 197);\n"
"")
        self.Fecha.setMinimumDate(QtCore.QDate(2025, 8, 6))
        self.Fecha.setObjectName("Fecha")
        self.labeldate = QtWidgets.QLabel(self.Bloque2)
        self.labeldate.setGeometry(QtCore.QRect(220, 180, 111, 16))
        self.labeldate.setStyleSheet("font: 10pt \"Tahoma\";\n"
"color: rgb(68, 169, 197);\n"
"")
        self.labeldate.setObjectName("labeldate")
        self.numberlabel = QtWidgets.QLabel(self.Bloque2)
        self.numberlabel.setGeometry(QtCore.QRect(220, 130, 141, 16))
        self.numberlabel.setStyleSheet("font: 10pt \"Tahoma\";\n"
"color: rgb(68, 169, 197);\n"
"")
        self.numberlabel.setObjectName("numberlabel")
        self.NumRobot = QtWidgets.QSpinBox(self.Bloque2)
        self.NumRobot.setGeometry(QtCore.QRect(220, 110, 42, 22))
        self.NumRobot.setStyleSheet("font: 12pt \"Tahoma\";\n"
"color: rgb(68, 169, 197);\n"
"")
        self.NumRobot.setMinimum(1)
        self.NumRobot.setMaximum(10)
        self.NumRobot.setObjectName("NumRobot")
        self.size = QtWidgets.QComboBox(self.Bloque2)
        self.size.setGeometry(QtCore.QRect(10, 160, 171, 22))
        self.size.setStyleSheet("font: 12pt \"Tahoma\";\n"
"color: rgb(68, 169, 197);\n"
"")
        self.size.setObjectName("size")
        self.size.addItem("")
        self.size.addItem("")
        self.size.addItem("")
        self.sizelabel = QtWidgets.QLabel(self.Bloque2)
        self.sizelabel.setGeometry(QtCore.QRect(10, 180, 161, 16))
        self.sizelabel.setStyleSheet("font: 10pt \"Tahoma\";\n"
"color: rgb(68, 169, 197);\n"
"")
        self.sizelabel.setObjectName("sizelabel")
        self.frame_2 = QtWidgets.QFrame(self.PrincipalFrame)
        self.frame_2.setGeometry(QtCore.QRect(50, 220, 361, 221))
        self.frame_2.setStyleSheet("background-color: rgb(249, 254, 146);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.levelbutton = QtWidgets.QPushButton(self.frame_2)
        self.levelbutton.setGeometry(QtCore.QRect(40, 70, 81, 61))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../recursos/octagon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.levelbutton.setIcon(icon3)
        self.levelbutton.setObjectName("levelbutton")
        self.levellabel = QtWidgets.QLabel(self.frame_2)
        self.levellabel.setGeometry(QtCore.QRect(170, 50, 141, 91))
        self.levellabel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.levellabel.setText("")
        self.levellabel.setObjectName("levellabel")
        self.frame_3 = QtWidgets.QFrame(self.PrincipalFrame)
        self.frame_3.setGeometry(QtCore.QRect(410, 0, 361, 441))
        self.frame_3.setStyleSheet("background-color: rgb(150, 220, 241);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.Plot = QtWidgets.QFrame(self.frame_3)
        self.Plot.setGeometry(QtCore.QRect(30, 230, 291, 171))
        self.Plot.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.Plot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Plot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Plot.setObjectName("Plot")
        self.camara = QtWidgets.QLabel(self.frame_3)
        self.camara.setGeometry(QtCore.QRect(30, 20, 291, 171))
        self.camara.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.camara.setText("")
        self.camara.setObjectName("camara")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SwarButton.setText(_translate("MainWindow", "Swarm"))
        self.TestButton.setText(_translate("MainWindow", "prueba"))
        self.AboutButton.setText(_translate("MainWindow", "about"))
        self.ResuButton.setText(_translate("MainWindow", "resultados"))
        self.ConexionButton.setText(_translate("MainWindow", "Conexion"))
        self.name.setText(_translate("MainWindow", "prueba"))
        self.dataname.setText(_translate("MainWindow", "Datos del experimento"))
        self.namelabel.setText(_translate("MainWindow", "Nombre del experimento"))
        self.labeldate.setText(_translate("MainWindow", "Fecha"))
        self.numberlabel.setText(_translate("MainWindow", "Cantidad de robots"))
        self.size.setItemText(0, _translate("MainWindow", "Grande(4x2 metros)"))
        self.size.setItemText(1, _translate("MainWindow", "Mediano(3x1.5 metros)"))
        self.size.setItemText(2, _translate("MainWindow", "Pequeño(2x1 metros)"))
        self.sizelabel.setText(_translate("MainWindow", "Tamaño del area controlada"))
        self.levelbutton.setText(_translate("MainWindow", "calibrar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
