# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\resultadosVista.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(380, 308)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.PrincipalFrame = QtWidgets.QFrame(self.centralwidget)
        self.PrincipalFrame.setGeometry(QtCore.QRect(0, 0, 781, 481))
        self.PrincipalFrame.setStyleSheet("background-color: rgb(237, 250, 254);")
        self.PrincipalFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PrincipalFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PrincipalFrame.setObjectName("PrincipalFrame")
        self.descartar = QtWidgets.QPushButton(self.PrincipalFrame)
        self.descartar.setGeometry(QtCore.QRect(130, 20, 75, 23))
        self.descartar.setStyleSheet("font: 10pt \"Tahoma\";\n"
"border-radius:20px;\n"
"background-color: rgb(196, 238, 250);")
        self.descartar.setObjectName("descartar")
        self.guardar = QtWidgets.QPushButton(self.PrincipalFrame)
        self.guardar.setGeometry(QtCore.QRect(40, 20, 75, 23))
        self.guardar.setStyleSheet("font: 10pt \"Tahoma\";\n"
"border-radius:40px;\n"
"background-color: rgb(196, 238, 250);")
        self.guardar.setObjectName("guardar")
        self.tableView = QtWidgets.QTableView(self.PrincipalFrame)
        self.tableView.setGeometry(QtCore.QRect(30, 60, 311, 211))
        self.tableView.setObjectName("tableView")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.descartar.setText(_translate("MainWindow", "Descartar"))
        self.guardar.setText(_translate("MainWindow", "Guardar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
